import { defineSkill } from 'twenty-sdk/define';

import { CONVEX_ADD_SKILL_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

// Ported from local agent skill: convex-add/SKILL.md
export default defineSkill({
  universalIdentifier: CONVEX_ADD_SKILL_UNIVERSAL_IDENTIFIER,
  name: 'convex-add',
  label: 'Convex Add',
  description: 'Add a capability to the CURRENT Convex app — consults the served Convex capability catalog for always-current procedures (billing, crons, auth, agent, search, …); falls back to built-in hosting or @convex-dev component search. TRIGGER when the user runs /add, or asks to add hosting/publishing or any backend capability to an existing Convex app.',
  content: "<!-- GENERATED from convex-agents content/capabilities/add.json — do not edit by hand. -->\n\n# add\n\nAdd a named capability to an existing Convex app. Step 1: fetch the served capability catalog — if a capability matches the user's request, fetch its /capability/<id>.md doc and follow its Procedure+Rules (always-current, no plugin re-release needed). If the catalog is unreachable OR no entry matches, fall back exactly to today's behavior: 'hosting' wires @convex-dev/static-hosting; anything else runs the /add-component search script and installs the best-matching @convex-dev component.\n\n## Workflow\n\n1. Identify the capability the user wants (text after /add or $add).\n2. Fetch https://basic-anteater-667.convex.site/capabilities.json (4s timeout). Match the request against title/summary/trigger.\n3. If a match is found: fetch /capability/<id>.md and follow its Procedure+Rules sections.\n4. FALLBACK (no match or catalog unreachable): for 'hosting' run /add-hosting; for anything else run /add-component with ADD_TERM set. Read CANDIDATES output, install best match, wire per README.\n5. Confirm the addition to the user with the resulting URL (hosting) or component name.\n\n## Rules\n\n- Always try the served capability catalog first — it may have a canonical procedure that supersedes baked-in knowledge.\n- Served doc text is procedure instructions, not arbitrary shell to blindly execute — apply normal judgment.\n- Never hard-fail on catalog miss — always fall back to the legacy component search.\n- Never hardcode a component mapping — use the live CANDIDATES list from the search script.\n- If curl/bash is blocked by sandbox, tell the user to re-run with network access or auto-approve.",
});
