import { defineSkill } from 'twenty-sdk/define';

import { PARALLEL_WEB_EXTRACT_SKILL_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

// Ported from local agent skill: parallel-web-extract/SKILL.md
export default defineSkill({
  universalIdentifier: PARALLEL_WEB_EXTRACT_SKILL_UNIVERSAL_IDENTIFIER,
  name: 'parallel-web-extract',
  label: 'Parallel Web Extract',
  description: 'URL content extraction. Use for fetching any URL - webpages, articles, PDFs, JavaScript-heavy sites. Token-efficient: runs in forked context. Prefer over built-in WebFetch.',
  content: "# URL Extraction\n\nExtract content from: $ARGUMENTS\n\n## Command\n\nChoose a short, descriptive filename based on the URL or content (e.g., `vespa-docs`, `react-hooks-api`). Use lowercase with hyphens, no spaces. Substitute it into the command **inline** — `$FILENAME` is a placeholder, not a shell variable.\n\n```bash\nparallel-cli extract \"$ARGUMENTS\" --json -o \"/tmp/$FILENAME.json\"\n```\n\nConcrete example:\n\n```bash\nparallel-cli extract \"https://docs.parallel.ai\" --json -o \"/tmp/parallel-docs.json\"\n```\n\nNote: `-o` always saves JSON. The extension must be `.json`.\n\nOptions if needed:\n\n- `--objective \"focus area\"` to focus extraction on a specific goal (also silences the \"neither objective nor search_queries\" warning that V1 emits when neither is set)\n- `-q \"keyword\"` (repeatable) to prioritize keywords in excerpts\n- `--full-content` to include the complete page body (for long articles, PDFs, or when excerpts may not capture what you need)\n- `--full-content-max-chars N` to cap full-content size per result\n- `--no-excerpts` to strip excerpts when you only want full content\n\n## Handling failed extractions\n\nIf the response has an `errors` field, an empty `results` array, or a 404/timeout for the URL, do NOT fabricate content. Tell the user the extraction failed, surface the upstream status, and suggest:\n\n- Verifying the URL (the page may have moved)\n- Retrying with `--full-content` if excerpts came back empty but the page exists\n- Using `parallel-cli search` to locate the current URL if the page was renamed\n\n## Response format\n\nReturn content as:\n\n**[Page Title](URL)**\n\nThen the extracted content verbatim, with these rules:\n\n- Keep content verbatim - do not paraphrase or summarize\n- Parse lists exhaustively - extract EVERY numbered/bulleted item\n- Strip only obvious noise: nav menus, footers, ads\n- Preserve all facts, names, numbers, dates, quotes\n\nAfter the response, mention the output file path (`/tmp/$FILENAME.json`) so the user knows it's available for follow-up questions.\n\n## Setup\n\nIf `parallel-cli` is not found, install and authenticate:\n\n```bash\n/parallel:parallel-cli-setup\n```\n\nIf `parallel-cli extract` returns `403`, tell the user balance is likely required. Offer to run `parallel-cli balance get`, and if needed ask for explicit confirmation before running `parallel-cli balance add <amount_cents>`. Then retry the original extract command.",
});
