import { defineSkill } from 'twenty-sdk/define';

import { PUBLISH_APP_SKILL_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

// Ported from local agent skill: publish-app/SKILL.md
export default defineSkill({
  universalIdentifier: PUBLISH_APP_SKILL_UNIVERSAL_IDENTIFIER,
  name: 'publish-app',
  label: 'Publish App',
  description: 'Use when the user wants to prepare or verify a Twenty app for npm or marketplace publication, including README/About copy, package metadata, defineApplication marketplace metadata, logos, screenshots, and public assets.',
  content: "# When To Use\n\nPick this skill when the user wants to make an existing Twenty app *presentable* — listing copy, branding, public assets, and publication. Representative triggers:\n\n- \"prepare my Twenty app for the marketplace\"\n- \"write the README for my Twenty app\"\n- \"publish my app to npm\"\n- \"add a logo / screenshots / marketplace metadata\"\n- \"set up `defineApplication` marketplace fields\"\n- \"review my app listing before going live\"\n- \"ship a new version of my published app\"\n\nDo not use this skill to scaffold (use `create-app`), to change app entities (use `develop-app`), to deploy a private build to a specific Twenty server (use `manage-app`), or to query workspace records (use `use-twenty-mcp`).\n\n# Publishing Checklist\n\nFor background on how Twenty apps work — the SDK packages, remotes, sync lifecycle, and rendering model — read `references/concepts/how-apps-work.md`. Cross-skill operating rules that apply to every Twenty app task are in `references/concepts/operating-rules.md`; they are authoritative and not restated per skill.\n\nUse `references/publish-app/prepare-for-app-store.md` for detailed README, marketplace copy, logo, screenshot, and public asset guidance.\n\nKeep the skill workflow concise:\n\n- Inspect `package.json`, `README.md`, `src/application-config.ts`, and `public/`.\n- For npm marketplace publication, ensure `package.json` has a valid bumped `version` and the `twenty-app` keyword.\n- In `defineApplication()`, verify marketplace-facing fields such as `displayName`, `description`, `author`, `category`, `logoUrl`, `screenshots`, `aboutDescription`, `websiteUrl`, `termsUrl`, `emailSupport`, and `issueReportUrl`.\n- Keep `logoUrl` and `screenshots` pointed at files in `public/`. Public assets must not contain secrets, private data, customer records, real tokens, or unreleased confidential material.\n- Remember that if `aboutDescription` is omitted, the marketplace uses the package `README.md` from npm for the About content. The About tab renders markdown text only: images and raw HTML are not rendered.\n- Validate with `yarn twenty dev:build`; publish with `yarn twenty app:publish` or `yarn twenty app:publish --tag <tag>`.\n\n# Boundaries\n\nUse `$manage-app` for remotes, deploys to a specific server, logs, troubleshooting, and CI/CD operations.\n\nUse `$develop-app` when the app entities themselves need to change before the listing can be accurate.\n\n# Docs\n\nIf the needed publishing detail is unclear, search the official Twenty docs at `https://docs.twenty.com` before guessing. When a Twenty docs MCP server is configured (`https://docs.twenty.com/mcp`), prefer searching through it. That server is an optional enhancement, not a requirement for this skill.",
});
