import { defineSkill } from 'twenty-sdk/define';

import { USE_TWENTY_MCP_SKILL_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

// Ported from local agent skill: use-twenty-mcp/SKILL.md
export default defineSkill({
  universalIdentifier: USE_TWENTY_MCP_SKILL_UNIVERSAL_IDENTIFIER,
  name: 'use-twenty-mcp',
  label: 'Use Twenty Mcp',
  description: 'Use when the user wants the agent to connect to an existing Twenty workspace through MCP, retrieve or inspect workspace records and metadata, or present Twenty CRM data as readable Markdown with formatted dates, values, record links, and compact tables instead of raw API output.',
  content: "# When To Use\n\nPick this skill when the user wants to read from or inspect a running Twenty workspace — not change app code. Representative triggers:\n\n- \"list all my companies / people / opportunities in Twenty\"\n- \"show me the records I created this week\"\n- \"what's in my Twenty workspace\"\n- \"connect my agent to my Twenty workspace\"\n- \"set up Twenty MCP for `myworkspace.twenty.com`\"\n- \"query the CRM for X\"\n- \"summarize my pipeline from Twenty\"\n- \"show me the fields on the company object\"\n\nDo not use this skill to scaffold an app (use `create-app`), to add or modify app entities (use `develop-app`), to operate an app (use `manage-app`), or to prepare marketplace assets (use `publish-app`).\n\n# What It Is\n\nTwenty MCP connects the agent to an existing Twenty workspace so it can inspect workspace data and metadata: records, objects, fields, schema, configuration, and related CRM context.\n\nThis is different from a Twenty app. Use `$create-app` when the user wants to scaffold a new app codebase, and `$develop-app` when the user wants to add app-defined features such as objects, fields, logic, layouts, or components.\n\nUse `$use-twenty-mcp` when the user wants to connect the agent to an already running workspace, retrieve or inspect workspace data, inspect metadata, or troubleshoot MCP access.\n\nDo not use MCP as the default way to customize a workspace. For example, prefer creating a new object through a Twenty app rather than directly through MCP. Use MCP for workspace customization only when the user explicitly asks to do it through MCP.\n\n# Setup\n\nUse `references/use-twenty-mcp/setup.md` for workspace URL normalization, MCP server configuration, OAuth guardrails, and setup troubleshooting.\n\n# Retrieval\n\nBefore retrieving, listing, searching, summarizing, or presenting workspace records, read `references/use-twenty-mcp/result-formatting.md`.\n\nApply that reference when selecting the right Twenty MCP workspace, querying records, building record links, formatting dates and values, and presenting readable Markdown instead of raw API output.\n\n# Output Contract\n\nBefore the final answer for retrieved workspace records:\n\n- If the tool output includes `recordReferences`, the first record-name column or record heading MUST link each display name back to Twenty.\n- Build links as `{workspaceOrigin}/object/{objectNameSingular}/{recordId}` using the selected workspace origin and the returned `recordReferences`.\n- If the workspace origin is not known, resolve it from the selected MCP server URL when possible. If it still cannot be resolved, state that direct record links need the workspace URL instead of inventing a host.\n- Never show unlinked record names in a record table when `recordReferences` and the workspace origin are available.",
});
