DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP POLICY IF EXISTS "DNC list is viewable by authenticated users" ON dnc_list;
DROP POLICY IF EXISTS "DNC list is insertable by authenticated users" ON dnc_list;
DROP POLICY IF EXISTS "Appointments are viewable by authenticated users" ON appointments;
DROP POLICY IF EXISTS "Appointments are insertable by authenticated users" ON appointments;
DROP POLICY IF EXISTS "Call logs are viewable by authenticated users" ON call_logs;
DROP POLICY IF EXISTS "Call logs are insertable by authenticated users" ON call_logs;
DROP POLICY IF EXISTS "Leads are viewable by authenticated users" ON leads;
DROP POLICY IF EXISTS "Leads are insertable by authenticated users" ON leads;
DROP POLICY IF EXISTS "Leads are updatable by the owner or admin" ON leads;
DROP POLICY IF EXISTS "Campaigns are viewable by authenticated users" ON campaigns;
DROP POLICY IF EXISTS "Campaigns are insertable by authenticated users" ON campaigns;
DROP POLICY IF EXISTS "Campaigns are updatable by the creator or admin" ON campaigns;
DROP POLICY IF EXISTS "Campaigns are deletable by admin" ON campaigns;
DROP POLICY IF EXISTS "Profiles are viewable by authenticated users" ON profiles;
DROP POLICY IF EXISTS "Profiles are updatable by the owner or admin" ON profiles;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP TABLE IF EXISTS dnc_list CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS call_logs CASCADE;
DROP TABLE IF EXISTS call_scripts CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS campaigns CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
